jobs:
- job: RichCodeNavUpload
  displayName: Rich Code Navigation Upload to Production
  pool: 
    vmImage: windows-2022
  steps:
  - template: install-dependencies.yml
  - task: RichCodeNavIndexer@0
    displayName: RichCodeNav Upload
    inputs:
      languages: 'csharp'
      environment: production
      isPrivateFeed: false
    continueOnError: true
